### ISSUE TITLE
Update metrics definitions based on recent discussion

### ISSUE THREAD

**Issue by illia-romanenko** [software-platform/monorepo#102]
AI: Rename: Builds to “Builds per week” since Monday.
AI: Align performance & stability to the builds in the build bar graph

**Comment by illia-romanenko** [comment]
@bootstraponline can we clarify this point a bit more:
>> AI: Rename: Builds to “Builds per week” since Monday.
for the user wouldn't that mean that this spikes are for weeks and not days?

To me it looks like it should be named something like:
"Builds this week (daily)" or "Daily builds" or "Builds per day" (and display information for the last 7 days)
or just 
"Builds this week" and add some axis names with a date (month/day - example 3/24.....3/25.... etc...)

What do you think?

**Comment by bootstraponline** [comment]
Summarizing the discussion today, I think `Builds (7 days)` makes sense. We can move this to be a number instead of a graph.

<img src="https://user-images.githubusercontent.com/1173057/77482111-699aa380-6de2-11ea-90c2-3f175156cf1f.png" width="30%" />
