### ISSUE TITLE
[core, web] Improve validation & introduce value_objects

### ISSUE THREAD

**Issue by illia-romanenko** [software-platform/monorepo#160]
To improve validation of passwords/emails we need to introduce the concept of value_objects - "immutable objects which have value equality and self-validation but no IDs" see https://github.com/GIfatahTH/states-rebuilder-examples/tree/master/008-clean_architecture_firebase_login & https://www.amazon.com/Implementing-Domain-Driven-Design-Vaughn-Vernon/dp/0321834577 - Chapter 5 - Entities -> Validation subsection.

Proposed changes:
1. [core] Introduce domain -> value_objects
2. [core] move Percent -> value_objects & validation to it if necessary
4. [core] Add EmailAddress & Password value objects making sure that they validate themselves in constructor (example - password minimum length = 6 characters) -> throw PasswordValidationException {
      PasswordValidationStatus/Code (enum) code;
}
5. [web] Introduce in AuthStore -> validateEmail & validatePassword methods that try to create value_objects (EmailAddress, Password) and if there is any Exception convert that Exception -> message using Exception code enum.
6. [web] On LoginPage (AuthForm) use validateEmail & validatePassword as validators for Input fields.
7. [web] In Login Use cases make sure that value_objects are used instead of String username/String password.

**Comment by bootstraponline** [comment]
https://resocoder.com/2020/03/09/flutter-firebase-ddd-course-1-domain-driven-design-principles/
https://resocoder.com/2020/03/13/flutter-firebase-ddd-course-2-authentication-value-objects/
https://resocoder.com/2020/03/17/flutter-firebase-ddd-course-3-auth-facade-interface/
https://resocoder.com/2020/03/20/flutter-firebase-ddd-course-4-modeling-the-sign-in-form-events-state/
https://resocoder.com/2020/03/30/flutter-firebase-ddd-course-5-sign-in-form-logic/

@illia-romanenko It may be worth reviewing these tutorials to see if any of this is helpful. This seems to be the exact use case we have. Firebase + Login + value objects.
