### ISSUE TITLE
Import Jenkins data to Firestore

### ISSUE THREAD

**Issue by bootstraponline** [software-platform/monorepo#4]
Develop a program that uses the Jenkins API to import all builds for a given job to Firebase. This should be idempotent. The program will run on a schedule and constantly update Firestore with the latest builds.

Name | Description
| --- | --- |
buildId | unique identifier of the build
buildDate | date the build was started
buildQueued | the amount of time the build spent waiting to execute
buildDuration | the amount of time the build took to execute (does not include queue time)
buildSuccessful | boolean for if the build was successful or not

**Comment by illia-romanenko** [comment]
Completed.
