### ISSUE TITLE
Automate sprint retro report

### ISSUE THREAD

**Issue by bootstraponline** [software-platform/monorepo#97]
Using the ZenHub API, it may be possible to automatically create a sprint retro report.

https://github.com/ZenHubIO/API

**Comment by illia-romanenko** [comment]
@bootstraponline is this about getting the list of closed issues from milestone? Or this is basically fixed with a Standuply retrospective report?

**Comment by bootstraponline** [comment]
>  this is basically fixed with a Standuply retrospective report?

this is fixed with Standuply 🙂
